services:
  cronicle:
    container_name: cronicle
    env_file:
      - .env
    build:
      context: .
      args:
        CRONICLE_VERSION: ${CRONICLE_VERSION}
        CRONICLE_BASE_URL: ${CRONICLE_BASE_URL}
        CRONICLE_TZ: ${CRONICLE_TZ}
        CRONICLE_FOREGROUND: ${CRONICLE_FOREGROUND}
        CRONICLE_ECHO: ${CRONICLE_ECHO}
        CRONICLE_COLOR: ${CRONICLE_COLOR}
        CRONICLE_DEBUG_LEVEL: ${CRONICLE_DEBUG_LEVEL}
        CRONICLE_HOSTNAME: ${CRONICLE_HOSTNAME}
    image: agileworksnet/cronicle-example
    restart: unless-stopped
    hostname: cronicle
    ports:
      - 3012:3012
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - network

networks:
  network:
    name: cronicle_network
