services:
  cronicle:
    container_name: cronicle
    build:
      context: .
      args:
        CRONICLE_base_url: http://localhost:3012
    image: fbaconsulting/cronicle
    restart: unless-stopped
    hostname: cronicle
    ports:
      - 3012:3012
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/data:/opt/cronicle/data
      - ./data/logs:/opt/cronicle/logs
      - ./data/plugins:/opt/cronicle/plugins
    environment:
      - TZ=Europe/Madrid
      - DEBUG=1
      - CRONICLE_foreground=1
      - CRONICLE_echo=1
      - CRONICLE_color=1
      - debug_level=1
      - HOSTNAME=main
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - network

networks:
  network:
    name: cronicle_network
