services:
  cronicle:
    container_name: cronicle
    build:
      context: .
      args:
        CRONICLE_VERSION: ${CRONICLE_VERSION}
        CRONICLE_base_url: ${CRONICLE_base_url}
        TZ: ${TZ}
        CRONICLE_foreground: ${CRONICLE_foreground}
        CRONICLE_echo: ${CRONICLE_echo}
        CRONICLE_color: ${CRONICLE_color}
        debug_level: ${debug_level}
        HOSTNAME: ${HOSTNAME}
    env_file:
      - .env
    image: agileworksnet/cronicle
    restart: unless-stopped
    hostname: cronicle
    ports:
      - 3012:3012
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/data:/opt/cronicle/data
      - ./data/logs:/opt/cronicle/logs
      - ./data/plugins:/opt/cronicle/plugins
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - network

networks:
  network:
    name: cronicle_network
